version: '3.0'

volumes:
    data:
        driver: local

networks: 
    simple-network:
        driver: bridge

services:
    api:
        ports: 
            - "3000:3000"
        container_name: api
        image: api
        restart: always
        build: 
            context: simple-node-api
            dockerfile: Dockerfile
        networks: 
            - simple-network
        depends_on: 
            - database

    client:
        ports: 
            - "4200:4200"
        container_name: client
        image: client
        restart: always
        build: 
            context: simple-client-list
            dockerfile: Dockerfile
        networks: 
            - simple-network
        depends_on: 
            - database
    
    database:
        container_name: database
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: node-crud
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes: 
            - data:/var/lib/postgresql/data
        networks: 
            - simple-network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "leaosomogyi@hotmail.com"
          PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
        ports:
          - "15432:80"
        depends_on:
          - database
        networks:
          - simple-network